### ISSUE TITLE
"For details:" Circular reference GitHub <=> seek4science

### ISSUE THREAD

**Issue by jonovik** [FAIRdom/JERMOntology#1]
https://github.com/SysMO-DB/JERMOntology
says

> Please visit http://seek4science.org/JERMOntology for details about contributing to the JERM

but
http://seek4science.org/JERMOntology
says only

> The ontology is available online at GitHub - https://github.com/SysMO-DB/JERMOntology

**Comment by stuzart** [comment]
Thanks for pointing this out. We intended having a dedicated page for
contributing suggestions and terms for the JERM ontology. For now I've
fixed it to point out our general contributors guide.
